name: example
version: 1.0.0+1
publish_to: none
description: A new Flutter project.

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^9.0.3
  cupertino_icons: ^1.0.2
  flutter_inappwebview: ^6.0.0
  url_launcher: ^6.1.4
  permission_handler: ^10.0.0
  web_view_ble:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true