name: web_view_ble
description: Add Bluetooth Low Energy Support in WebView Flutter for Android and iOS
version: 0.1.0
homepage: https://github.com/rohitsangwan01/web_view_ble
repository: https://github.com/rohitsangwan01/web_view_ble
issue_tracker: https://github.com/rohitsangwan01/web_view_ble/issues

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  universal_ble: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

platforms:
  android:
  ios:

flutter:
  uses-material-design: true
  assets:
    - web_ble/stringview.js
    - web_ble/WBUtils.js
    - web_ble/WBEventTarget.js
    - web_ble/WBBluetoothUUID.js
    - web_ble/WBDevice.js
    - web_ble/WBBluetoothRemoteGATTServer.js
    - web_ble/WBBluetoothRemoteGATTService.js
    - web_ble/WBBluetoothRemoteGATTCharacteristic.js
    - web_ble/WBPolyfill.js